extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - prettier/babel
  - prettier/react
plugins:
  - babel
  - prettier
  - react
settings:
  react:
    pragma: jsx
    version: detect
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  env:
    es6: true
    node: true
  rules:
    prettier/prettier: error
