version: 2
jobs:
  build:
    working_directory: ~/shaarp
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: add-pika-pack
          command: yarn global add @pika/pack
      - run:
          name: build
          command: pack build
